services:
  jdocmunch:
    build: .
    image: jdocmunch-service:latest
    container_name: jdocmunch-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - jdocmunch_data:/root/.local/share/jdocmunch
      - ./.env:/app/.env
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JDOCMUNCH_EMBEDDING_PROVIDER=gemini
    networks:
      - general_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ssjdocmunchss.rule=Host(`ssjdocmunchss.odontolab.co`)"
        - "traefik.http.routers.ssjdocmunchss.entrypoints=websecure"
        - "traefik.http.routers.ssjdocmunchss.tls.certresolver=myresolver"
        - "traefik.http.services.ssjdocmunchss.loadbalancer.server.port=3000"
        - "traefik.docker.network=general_network"

networks:
  general_network:
    external: true

volumes:
  jdocmunch_data: {}
